# Generated by Django 6.0.3 on 2026-04-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(blank=True, max_length=100, verbose_name='ブランド名')),
                ('item_name', models.CharField(max_length=100, verbose_name='アイテム名')),
                ('price', models.IntegerField(default=0, verbose_name='金額')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='カラー')),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/', verbose_name='アイテム画像')),
                ('style', models.CharField(blank=True, choices=[('simple', '#シンプル'), ('kireime', '#きれいめ'), ('aline', '#Aライン'), ('iline', '#Iライン'), ('sale', '#セール')], max_length=20, verbose_name='スタイル')),
                ('kokkaku', models.CharField(blank=True, choices=[('straight', '#ストレート'), ('wave', '#ウェーブ'), ('natural', '#ナチュラル')], max_length=20, verbose_name='骨格タイプ')),
                ('personal_color', models.CharField(blank=True, choices=[('yebe', '#イエベ'), ('burube', '#ブルベ'), ('neutral', '#ニュートラル')], max_length=20, verbose_name='パーソナルカラー')),
                ('free_tags', models.TextField(blank=True, verbose_name='自由記入タグ')),
            ],
        ),
    ]
