# Generated by Django 6.0.3 on 2026-04-02 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, verbose_name='アイテム説明'),
        ),
        migrations.AddField(
            model_name='item',
            name='detail_image',
            field=models.ImageField(blank=True, null=True, upload_to='details/', verbose_name='詳細画像'),
        ),
        migrations.AddField(
            model_name='item',
            name='details_text',
            field=models.TextField(blank=True, verbose_name='アイテム詳細'),
        ),
        migrations.AlterField(
            model_name='item',
            name='kokkaku',
            field=models.CharField(blank=True, max_length=100, verbose_name='骨格タイプ'),
        ),
        migrations.AlterField(
            model_name='item',
            name='personal_color',
            field=models.CharField(blank=True, max_length=100, verbose_name='パーソナルカラー'),
        ),
        migrations.AlterField(
            model_name='item',
            name='style',
            field=models.CharField(blank=True, max_length=100, verbose_name='スタイル'),
        ),
    ]
