# Generated by Django 6.0.3 on 2026-04-10 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0002_item_description_item_detail_image_item_details_text_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsiderationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50, verbose_name='サイズ')),
                ('color', models.CharField(max_length=50, verbose_name='カラー')),
                ('quantity', models.IntegerField(default=1, verbose_name='数量')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='closet.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemAdditionalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='items/extra/', verbose_name='追加詳細画像')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='closet.item')),
            ],
        ),
    ]
