# Generated by Django 6.0.3 on 2026-05-12 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0005_tag_item_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='購入日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='購入者')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=10, verbose_name='サイズ')),
                ('color', models.CharField(max_length=20, verbose_name='カラー')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='数量')),
                ('price_at_purchase', models.IntegerField(verbose_name='購入時の価格')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='closet.item', verbose_name='商品')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='closet.order', verbose_name='注文')),
            ],
        ),
        migrations.DeleteModel(
            name='PurchaseItem',
        ),
    ]
