# Generated by Django 6.0.3 on 2026-05-28 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0007_favorite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True, verbose_name='購入日時')),
                ('size', models.CharField(default='未選択', max_length=50, verbose_name='サイズ')),
                ('color', models.CharField(default='未選択', max_length=50, verbose_name='カラー')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='closet.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
