# Generated by Django 6.0.3 on 2026-05-31 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0008_purchaseitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
