# Generated by Django 6.0.3 on 2026-06-01 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0009_item_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='considerationitem',
            name='added_at',
        ),
        migrations.AlterField(
            model_name='considerationitem',
            name='color',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='considerationitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='considerationitem',
            name='size',
            field=models.CharField(max_length=50),
        ),
    ]
