# Generated by Django 6.0.3 on 2026-06-04 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0011_considerationitem_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemadditionalimage',
            name='image_type',
            field=models.IntegerField(choices=[(0, 'モデル着用'), (1, 'ディテール'), (2, 'コーディネート'), (3, 'バックスタイル')], default=0, verbose_name='画像タイプ'),
        ),
    ]
