# Generated by Django 6.0.3 on 2026-06-04 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0012_itemadditionalimage_image_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='price_at_purchase',
            field=models.IntegerField(default=0, verbose_name='購入時の価格'),
        ),
    ]
