# Generated by Django 6.0.3 on 2026-06-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0013_purchaseitem_price_at_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='公開状態'),
        ),
    ]
