# Generated by Django 6.0.3 on 2026-06-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0014_item_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='detail_image1',
            field=models.ImageField(blank=True, null=True, upload_to='items/', verbose_name='生地のアップ'),
        ),
        migrations.AddField(
            model_name='item',
            name='detail_image2',
            field=models.ImageField(blank=True, null=True, upload_to='items/', verbose_name='裏地'),
        ),
        migrations.AddField(
            model_name='item',
            name='detail_image3',
            field=models.ImageField(blank=True, null=True, upload_to='items/', verbose_name='ポケット等の詳細'),
        ),
    ]
