# Generated by Django 6.0.3 on 2026-06-29 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0015_item_detail_image1_item_detail_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='material',
            field=models.CharField(blank=True, max_length=200, verbose_name='素材'),
        ),
        migrations.AddField(
            model_name='item',
            name='size_details',
            field=models.TextField(blank=True, verbose_name='サイズ詳細'),
        ),
    ]
