# Generated by Django 6.0.3 on 2026-07-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0016_item_material_item_size_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, choices=[('tops', 'トップス'), ('bottoms', 'ボトムス'), ('outer', 'アウター')], max_length=20, verbose_name='カテゴリ'),
        ),
    ]
